#!/usr/bin/env python2.4
import findrox; findrox.version(1, 9, 13)

import os
import rox
from rox.settings import Setting, Settings
from rox.OptionsBox import OptionsBox

FONT_ANTIALIASING_KEY = "/desktop/gnome/font_rendering/antialiasing"
FONT_HINTING_KEY =	"/desktop/gnome/font_rendering/hinting"
FONT_RGBA_ORDER_KEY =	"/desktop/gnome/font_rendering/rgba_order"
FONT_DPI_KEY =		"/desktop/gnome/font_rendering/dpi"

antialias_options = [ 'none', 'grayscale', 'rgba' ]
font_hint_options = [ 'none', 'slight', 'medium', 'full' ]
rgb_order_options = [ 'rgb', 'bgr', 'vrgb', 'vbgr' ]

settings = Settings()

class FontSetting(Setting):
	def __init__(self, name, default, gconf_key = None):
		if name.find('Font') != -1:
			garbage = True
		else:
			garbage = False
		Setting.__init__(self, name, default, settings, garbage, gconf_key)

class DPISetting(FontSetting):
	def post_notify_hook(self):
		self.settings.bus.SetInt('Xft/DPI', self.int_value * 1024)

FontSetting('Gtk/FontName', "Sans 10", "font_name")
FontSetting('ROX/DesktopFont', "Sans 10")
FontSetting('ROX/WindowTitleFont', "Sans 10")
FontSetting('ROX/MonospaceFontName', "Monospace 10", "monospace_font_name")
DPISetting('ROX/DPI', 72)
FontSetting('Xft/Antialias', 1)
FontSetting('Xft/Hinting', 1)
#FontSetting('Xft/HintStyle', 1)
FontSetting('Xft/RGBA', "rgb")


box = OptionsBox(settings, os.path.join(rox.app_dir, 'Options.xml'))
box.open()

rox.mainloop()
